name: Flats
api-version: 1.13
version: '${version}'
main: de.nvclas.flats.Flats
authors: [ nvclas ]
description: Creating flats with build permission

libraries:
  - org.flywaydb:flyway-core:10.0.0 # Flyway dependency for database migrations

commands:
  flats:
    description: Plugin base command
