name: Flats
api-version: 1.13
version: '${version}'
main: de.nvclas.flats.Flats
authors: [ nvclas ]
description: Creating flats with build permission

libraries:
  - org.flywaydb:flyway-core:${flywayVersion} # Flyway dependency for database migrations
  - org.xerial:sqlite-jdbc:${sqliteVersion}
  - com.github.ben-manes.caffeine:caffeine:${caffeineVersion} # Caffeine dependency for caching

commands:
  flats:
    description: Plugin base command
