name: Flats
api-version: 1.13
version: '${version}'
main: de.nvclas.flats.Flats
authors: [ nvclas ]
description: Creating flats with build permission

commands:
  flats:
    description: Plugin base command