# Sets the language for the plugin
# Supported languages:
#   - English (US):           en_us
#   - Español (España):       es_es
#   - Português (Portugal):   pt_pt
#   - Français (France):      fr_fr
#   - Deutsch (Deutschland):  de_de
#   - Italiano (Italia):      it_it
#   - Polski (Polska):        pl_pl
#   - Nederlands (Nederland): nl_nl
#   - 日本語 (日本):            ja_jp
#   - Svenska (Sverige):      sv_se
#   - Română (România):       ro_ro
#   - Ελληνικά (Ελλάδα):      el_gr
#   - Magyar (Magyarország):  hu_hu
#   - Українська (Україна):   uk_ua
language: en_us

# Sets the auto save interval for all flats in seconds
# 600 seconds equal 10 minutes
# Set to 0 to disable auto save
autoSaveInterval: 600

# Sets the maximum volume of a flat in blocks
maxFlatSize: 10000

# Sets the maximum number of claimable flats per player
maxClaimableFlats: 3

# Set this to true if you prefer to use fine-grained permissions using a permission management plugin
useAdvancedPermissions: false

# Automatic gamemode change on flat entering or leaving
enableAutoGamemode: false # true if enabled, false if disabled
insideFlatGamemode: creative # Possible values: survival, creative, adventure, spectator
outsideFlatGamemode: adventure # Possible values: survival, creative, adventure, spectator
