# Sets the language for the plugin
# Supported are: en_us, de_de, fr_fr, es_es
language: en_us

# Sets the auto save interval for all flats in seconds
# 600 seconds equal 10 minutes
# Set to 0 to disable auto save
autoSaveInterval: 600

# Sets the maximum volume of a flat in blocks
maxFlatSize: 10000

# Sets the maximum number of claimable flats per player
maxClaimableFlats: 3

# Automatic gamemode change on flat entering or leaving
enableAutoGamemode: false # true if enabled, false if disabled
insideFlatGamemode: creative # Possible values: survival, creative, adventure, spectator
outsideFlatGamemode: adventure # Possible values: survival, creative, adventure, spectator