[versions]
annotations = "26.1.+"
lombok = "9.5.+"
runPaper = "3.1.+"
paperweight-userdev = "2.0.+"
paper = "1.21.11-R0.1-SNAPSHOT"
mockbukkit = "4.116.+"
junit-jupiter = "5.13.+"
junit-platform-launcher = "1.13.+"
shadow = "9.6.+"
worldguard = "7.0.17"
vault = "1.7.+"
treasury = "2.0.+"

# Specific versions for plugin.yml
sqlite = "3.51.3.0"
flyway = "12.2.0"
caffeine = "3.2.4"
mysql = "26.7.0"
mariadb = "3.5.10"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
mockbukkit = { group = "org.mockbukkit.mockbukkit", name = "mockbukkit-v1.21", version.ref = "mockbukkit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform-launcher" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
mysql = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysql" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version.ref = "vault" }
treasury = { group = "me.lokka30", name = "treasury-api", version.ref = "treasury" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard" }

[plugins]
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
