name: Increment Version on Dev Push

on:
  push:
    branches:
      - dev

jobs:
  increment-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Extract current version
        id: extract_version
        run: |
          CURRENT_VERSION=$(grep '^version' build.gradle.kts | sed -E 's/^version[[:space:]]*=[[:space:]]*\"([^\"]+)\"/\1/')
          echo "Current version: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          # Split version into parts
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"

          # Increment patch version
          PATCH=$((VERSION_PARTS[2] + 1))

          # Construct new version
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

          # Update version in build.gradle.kts
          sed -i "s/version = \"$CURRENT_VERSION\"/version = \"$NEW_VERSION\"/" build.gradle.kts

      - name: Amend commit and force push changes
        run: |
          git add build.gradle.kts
          git commit --amend --no-edit
          git push --force
